/** Export actions for loading artifacts, refreshing progress, and starting exports. */

/** Read the export option checkboxes from the DOM.
 *  Only `excludeHumans` is backed by the backend right now — it triggers a
 *  CSV regeneration via POST /api/export/start. Burst-duplicate and
 *  split-by-site options were removed from the UI because they had no
 *  backend support; re-add them here once the backend wires them up. */
function readExportOptions() {
  return {
    excludeHumans: document.getElementById("opt-humans")
      ?.querySelector(".export-option-cb")?.checked ?? true
  };
}

/** Read the date + camera filters from the DOM (returns null values when not set). */
function readExportFilters() {
  return {
    dateFrom: document.getElementById("dp-text-export-start")?.value?.trim() || null,
    dateTo: document.getElementById("dp-text-export-end")?.value?.trim() || null,
    cameraFilter: (() => {
      const v = document.getElementById("export-camera-filter")?.value;
      return v && v !== "All Sites" ? v : null;
    })()
  };
}

export function createExportActions(app, api, renderApi) {
  async function loadExportData({ showToastOnError = false } = {}) {
    try {
      const [validation, data] = await Promise.all([
        app.state.validationData
          ? Promise.resolve(app.state.validationData)
          : api.getValidationIssues(),
        api.startExportRequest()
      ]);
      if (!app.state.validationData) app.features.validate.applyValidationData(validation);
      renderApi.applyExportData(data, validation);
      renderApi.syncDriveConnectionBanner();
      app.state.pageLoadState.export = true;
      return data;
    } catch (error) {
      renderApi.applyExportData(null, app.state.validationData);
      renderApi.syncDriveConnectionBanner();
      if (showToastOnError) app.showToast(error.message || "Unable to load export artifacts", "warn");
      return null;
    }
  }

  async function beginExport() {
    const wrap = document.getElementById("export-progress-wrap");
    const fill = document.getElementById("export-progress-fill");
    const pct  = document.getElementById("export-progress-pct");
    const text = document.getElementById("export-progress-text");
    const sub  = document.getElementById("export-progress-sub");

    if (wrap) wrap.style.display = "block";
    if (fill) fill.style.width = "20%";
    if (pct)  pct.textContent  = "20%";
    if (text) text.textContent = "Reading export artifacts…";
    if (sub)  sub.textContent  = "Inspecting generated by_site CSV files…";

    try {
      const options = readExportOptions();
      const filters = readExportFilters();

      // POST options/filters to the backend so future versions can act on them.
      const data = await api.startExportRequest({ ...options, ...filters });
      renderApi.applyExportData(data, app.state.validationData);

      if (fill) fill.style.width = "100%";
      if (pct)  pct.textContent  = "100%";
      if (text) text.textContent =
        data?.status === "ready" ? "Export artifacts ready" : "No export artifacts available";

      const driveConnected = Boolean(app.state.driveConnected);
      if (sub) {
        sub.textContent = driveConnected
          ? "Drive upload is not yet implemented — use the Download buttons below to save files locally."
          : "Google Drive not connected. Use the Download buttons below to save files locally.";
      }

      app.showToast(
        data?.message || "Export artifacts refreshed",
        data?.status === "ready" ? "success" : "warn"
      );
    } catch (error) {
      if (fill) fill.style.width = "0%";
      if (pct)  pct.textContent  = "0%";
      if (text) text.textContent = "Unable to load export artifacts";
      if (sub)  sub.textContent  = error.message || "Backend request failed";
      app.showToast(error.message || "Unable to load export artifacts", "warn");
    }
  }

  async function downloadFile(fileName) {
    try {
      app.showToast(`Downloading ${fileName}…`, "");
      await api.downloadExportFile(fileName);
      app.showToast(`${fileName} downloaded`, "success");
    } catch (error) {
      app.showToast(error.message || `Failed to download ${fileName}`, "warn");
    }
  }

  return {
    beginExport,
    downloadFile,

    // Local "Apply Options" action: regenerate the export files based on the
    // selected options (currently excludeHumans), refresh the summary + file
    // rows, then let the user download via the per-file Download buttons.
    // Reuses beginExport(); adds button feedback so the user sees it worked.
    applyExportOptions: async () => {
      const btn = document.getElementById("export-apply-btn");
      const originalHTML = btn?.innerHTML;
      if (btn) {
        btn.disabled = true;
        btn.innerHTML = "Updating…";
      }
      try {
        await beginExport();
      } finally {
        if (btn) {
          btn.disabled = false;
          if (originalHTML) btn.innerHTML = originalHTML;
        }
      }
    },

    closeExportModal: (event) => {
      if (!event || event.target === event.currentTarget)
        document.getElementById("export-modal-overlay")?.classList.remove("open");
    },

    confirmExport: () => {
      document.getElementById("export-modal-overlay")?.classList.remove("open");
      void beginExport();
    },

    loadExportData,

    selectFormat: (format) => {
      app.state.selectedFormat = format;
      document.querySelectorAll(".export-fmt-card")
        .forEach((card) => card.classList.remove("selected"));
      document.getElementById(`fmt-${format}`)?.classList.add("selected");
      renderApi.syncExportFilenamePreview();
    },

    startExport: async () => {
      // Guard: validate data must be present (warn user but don't block)
      if (!app.state.validationData) {
        await app.features.validate.loadValidationData();
      }
      const hasIssues =
        Number(app.state.validationData?.outside_range     || 0) > 0 ||
        Number(app.state.validationData?.unprocessed       || 0) > 0 ||
        Number(app.state.validationData?.column_issue_count || 0) > 0;

      if (hasIssues) {
        document.getElementById("export-modal-overlay")?.classList.add("open");
        return;
      }
      void beginExport();
    },

    toggleExportFilter: () =>
      document.getElementById("export-filter-body")?.classList.toggle("open"),

    toggleExportOption: (row, id, checkboxEl = null, event = null) => {
      const checkbox = checkboxEl || row.querySelector(".export-option-cb");
      if (!checkbox) return;
      // If the click landed on the checkbox itself, the browser has already
      // toggled `checked` — don't flip it again (that double-toggle is why
      // clicking the box appeared to do nothing). Only flip manually when the
      // click came from elsewhere in the row (label text, padding, badge).
      const clickedCheckbox = event && event.target === checkbox;
      if (!clickedCheckbox) checkbox.checked = !checkbox.checked;
      row.classList.toggle("checked", checkbox.checked);
    }
  };
}
