/** Export rendering for artifact summaries, rows, and filename previews. */
import { setHTML, setText } from "../../utils/dom.js";
import { escapeHtml, formatNumber } from "../../utils/format.js";

export function createExportRender(app) {
  function buildExportFolderRows(files = []) {
    // Hide the "Needs review" helper file (review_needed.csv) from the UI —
    // the file is still generated by the backend, just not surfaced here.
    files = files.filter((file) => (file.name || "") !== "review_needed.csv");
    if (!files.length) {
      return `<div class="export-folder-row">
        <div class="export-folder-icon">
          <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="#718096" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
            <path d="M22 19a2 2 0 0 1-2 2H4a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h5l2 3h9a2 2 0 0 1 2 2z"/>
          </svg>
        </div>
        <div style="flex:1;min-width:0">
          <div class="export-folder-name">No export files available</div>
          <div class="export-folder-sub">Run the pipeline to generate data/outputs/by_location files.</div>
        </div>
      </div>`;
    }

    return files.map((file) => {
      // Prefer the friendly label the backend supplies (e.g. "Final results"),
      // and fall back to the bare filename without its .csv extension.
      const rawLabel    = file.label || (file.name || "Unknown").replace(/\.csv$/i, "");
      const displayName = escapeHtml(rawLabel);
      const safeName    = escapeHtml(file.name || "");
      const isPrimary   = (file.name || "") === "final_results.csv";
      // Subline avoids exposing internal paths — non-technical users only
      // need the row count and the file's role.
      const sublineText = isPrimary
        ? `${formatNumber(file.rows)} rows · main file for researchers`
        : `${formatNumber(file.rows)} rows`;
      const mainBadge = isPrimary
        ? `<span style="margin-left:8px;font-size:11px;font-weight:600;color:#2B6CB0;background:#EBF8FF;border:1px solid #BEE3F8;padding:2px 7px;border-radius:6px">Main file</span>`
        : "";

      return `<div class="export-folder-row"${isPrimary ? ' style="background:#F7FAFC"' : ""}>
        <div class="export-folder-icon">
          <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="#2B6CB0" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
            <path d="M22 19a2 2 0 0 1-2 2H4a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h5l2 3h9a2 2 0 0 1 2 2z"/>
          </svg>
        </div>
        <div style="flex:1;min-width:0">
          <div class="export-folder-name">${displayName}${mainBadge}</div>
          <div class="export-folder-sub">${sublineText}</div>
        </div>
        <div class="export-folder-actions">
          <span class="export-sync-badge synced">
            <svg width="10" height="10" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="3" stroke-linecap="round" stroke-linejoin="round">
              <polyline points="20 6 9 17 4 12"/>
            </svg>
            Ready
          </span>
          <button
            class="export-folder-view-btn export-download-btn"
            data-filename="${safeName}"
            title="Download ${safeName}"
          >
            Download
          </button>
        </div>
      </div>`;
    }).join("");
  }

  function syncExportFilenamePreview() {
    const input   = document.getElementById("export-filename");
    const preview = document.getElementById("export-filename-preview");
    if (input && preview) preview.textContent = `${input.value}.${app.state.selectedFormat}`;
  }

  /**
   * Show or hide the "Google Drive Not Connected" banner inside the delivery card.
   * Call this whenever drive connection state changes or on page load.
   */
  function syncDriveConnectionBanner() {
    const banner  = document.getElementById("export-disconnected-banner");
    const content = document.getElementById("export-drive-content");
    const mainBtn = document.getElementById("export-main-btn");
    const connected = Boolean(app.state.driveConnected);

    if (banner)  banner.style.display  = connected ? "none"  : "flex";
    if (content) content.style.opacity = connected ? "1"     : "0.55";

    // The green "Export to Google Drive" button is only usable once Drive is
    // connected. When disconnected it is disabled; users export locally via
    // the Download buttons (which are never disabled) after clicking Apply.
    if (mainBtn) {
      mainBtn.disabled = !connected;
      mainBtn.title = connected
        ? ""
        : "Connect Google Drive to export there. To save locally, use the Download buttons above.";
    }
  }

  function applyExportData(data, validation = app.state.validationData) {
    app.state.exportData = data;
    setText("export-val-total", formatNumber(data?.total_rows || 0));
    setText("export-val-human", formatNumber(data?.human_detections_excluded || 0));
    setHTML("export-folder-list", buildExportFolderRows(data?.files || []));

    const issueCount =
      Number(validation?.outside_range      || 0) +
      Number(validation?.unprocessed        || 0) +
      Number(validation?.column_issue_count || 0);

    setText(
      "export-status-title",
      validation
        ? `${formatNumber(issueCount)} validation issue${issueCount === 1 ? "" : "s"} found`
        : "Validation checks are clear"
    );
    setText(
      "export-status-sub",
      validation
        ? `${formatNumber(validation?.unprocessed || 0)} unprocessed images and ` +
          `${formatNumber(validation?.outside_range || 0)} out-of-range timestamps — ` +
          `these records will be excluded from the export automatically`
        : "Current export artifacts are ready with no validation exclusions."
    );
    setHTML(
      "export-main-btn",
      `<svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round">
        <polyline points="22 12 18 12 15 21 9 3 6 12 2 12"/>
      </svg>Export ${formatNumber(data?.total_rows || 0)} Records to Google Drive`
    );
    const humanExcluded = data?.human_detections_excluded || 0;
    setText("badge-human-rows", (humanExcluded ? "-" : "") + formatNumber(humanExcluded) + " rows");
    syncExportFilenamePreview();
    syncDriveConnectionBanner();
  }

  return {
    applyExportData,
    syncExportFilenamePreview,
    syncDriveConnectionBanner
  };
}
