/** Export actions for loading artifacts, refreshing progress, and starting exports. */
export function createExportActions(app, api, renderApi) {
  async function loadExportData({ showToastOnError = false } = {}) {
    try {
      const [validation, data] = await Promise.all([
        app.state.validationData ? Promise.resolve(app.state.validationData) : api.getValidationIssues(),
        api.startExportRequest()
      ]);
      if (!app.state.validationData) app.features.validate.applyValidationData(validation);
      renderApi.applyExportData(data, validation);
      app.state.pageLoadState.export = true;
      return data;
    } catch (error) {
      renderApi.applyExportData(null, app.state.validationData);
      if (showToastOnError) app.showToast(error.message || "Unable to load export artifacts", "warn");
      return null;
    }
  }

  async function beginExport() {
    const wrap = document.getElementById("export-progress-wrap");
    const fill = document.getElementById("export-progress-fill");
    const pct = document.getElementById("export-progress-pct");
    const text = document.getElementById("export-progress-text");
    const sub = document.getElementById("export-progress-sub");
    if (wrap) wrap.style.display = "block";
    if (fill) fill.style.width = "20%";
    if (pct) pct.textContent = "20%";
    if (text) text.textContent = "Reading export artifacts…";
    if (sub) sub.textContent = "Inspecting generated by_site CSV files…";

    try {
      const data = await api.startExportRequest();
      renderApi.applyExportData(data, app.state.validationData);
      if (fill) fill.style.width = "100%";
      if (pct) pct.textContent = "100%";
      if (text) text.textContent = data?.status === "ready" ? "Export artifacts ready" : "No export artifacts available";
      if (sub) sub.textContent = data?.note || "Upload integration is not wired yet.";
      app.showToast(data?.message || "Export artifacts refreshed", data?.status === "ready" ? "success" : "warn");
    } catch (error) {
      if (fill) fill.style.width = "0%";
      if (pct) pct.textContent = "0%";
      if (text) text.textContent = "Unable to load export artifacts";
      if (sub) sub.textContent = error.message || "Backend request failed";
      app.showToast(error.message || "Unable to load export artifacts", "warn");
    }
  }

  return {
    beginExport,
    closeExportModal: (event) => {
      if (!event || event.target === event.currentTarget) document.getElementById("export-modal-overlay")?.classList.remove("active");
    },
    confirmExport: () => {
      document.getElementById("export-modal-overlay")?.classList.remove("active");
      void beginExport();
    },
    loadExportData,
    selectFormat: (format) => {
      app.state.selectedFormat = format;
      document.querySelectorAll(".export-fmt-card").forEach((card) => card.classList.remove("selected"));
      document.getElementById(`fmt-${format}`)?.classList.add("selected");
      renderApi.syncExportFilenamePreview();
    },
    startExport: async () => {
      if (!app.state.driveConnected) {
        app.showToast("Connect Google Drive first", "warn");
        return;
      }
      if (!app.state.validationData) {
        await app.features.validate.loadValidationData();
      }
      const hasIssues = Number(app.state.validationData?.outside_range || 0) > 0 || Number(app.state.validationData?.unprocessed || 0) > 0 || Number(app.state.validationData?.column_issue_count || 0) > 0;
      if (hasIssues) {
        document.getElementById("export-modal-overlay")?.classList.add("active");
        return;
      }
      void beginExport();
    },
    toggleExportFilter: () => document.getElementById("export-filter-body")?.classList.toggle("open"),
    toggleExportOption: (row, id, checkboxEl = null) => {
      const checkbox = checkboxEl || row.querySelector(".export-option-cb");
      if (!checkbox) return;
      if (!checkboxEl) checkbox.checked = !checkbox.checked;
      row.classList.toggle("checked", checkbox.checked);
    }
  };
}
