/** App bootstrap helper for exposing legacy window callbacks expected by the markup. */
import { closeConfirmModal, confirmModalOK } from "../components/common/confirmModal.js";
import { openDP, pickDate } from "../components/common/datePickers.js";

export function bindGlobals(app, showPage) {
  app.showPage = showPage;
  window.showPage = showPage;
  window.showPageFromReview = showPage;
  window.showToast = app.showToast;
  window.closeConfirmModal = closeConfirmModal;
  window.confirmModalOK = confirmModalOK;
  window.openDP = openDP;
  window.pickDate = pickDate;
  window.selectProject = app.features.auth.selectProject;
  // Login screen only advances forward via a single "Continue" button.
  window.goToStep2 = () => app.features.auth.setLoginStep(2);
  window.startGoogleSignIn = app.features.auth.startGoogleSignIn;
  window.continueWithoutGoogleDrive = app.features.auth.continueWithoutGoogleDrive;
  window.confirmDrive = app.features.auth.confirmDrive;
  window.switchAccount = app.features.auth.switchAccount;
  window.openDriveModal = app.features.auth.openDriveModal;
  window.reconnectDrive = app.features.auth.reconnectDrive;
  window.switchUploadTab = app.features.drive.switchUploadTab;
  window.selectLocCard = app.features.drive.selectLocCard;
  window.selectDriveLocCard = app.features.drive.selectDriveLocCard;
  window.handleDriveFolderSelect = app.features.drive.handleDriveFolderSelect;
  window.handleDriveSyncSettingsChange = app.features.drive.handleDriveSyncSettingsChange;
  window.handleDriveDateRangeChange = app.features.drive.handleDriveDateRangeChange;
  window.refreshDriveFolders = app.features.drive.refreshDriveFolders;
  window.syncDriveManualSelectionState = app.features.drive.syncDriveManualSelectionState;
  window.syncDriveCustomSiteState = app.features.drive.syncDriveCustomSiteState;
  window.handleDriveManualSelectionKeydown = app.features.drive.handleDriveManualSelectionKeydown;
  window.applyManualDriveFolderSelection = app.features.drive.applyManualDriveFolderSelection;
  window.handleDriveCustomSiteKeydown = app.features.drive.handleDriveCustomSiteKeydown;
  window.applyDriveCustomSite = app.features.drive.applyDriveCustomSite;
  window.openDriveSiteModal = app.features.drive.openDriveSiteModal;
  window.closeDriveSiteModal = app.features.drive.closeDriveSiteModal;
  window.selectDriveAutoSite = app.features.drive.selectDriveAutoSite;
  window.triggerSync = app.features.drive.triggerSync;
  window.loadDriveSyncStatus = app.features.drive.loadDriveSyncStatus;
  window.updateSlider = app.features.pipeline.updateSlider;
  window.toggleRunModel = app.features.pipeline.toggleRunModel;
  window.toggleDriveRunModel = app.features.pipeline.toggleDriveRunModel;
  window.toggleRunDetail = app.features.pipeline.toggleRunDetail;
  window.downloadPipelineResult = app.features.pipeline.downloadPipelineResult;
  window.navigateReview = app.features.review.navigateReview;
  window.reviewAction = app.features.review.reviewAction;
  window.askFlagConfirm = app.features.review.askFlagConfirm;
  window.setRFilter = app.features.review.setRFilter;
  window.toggleHumanFilter = app.features.review.toggleHumanFilter;
  window.toggleSort = app.features.review.toggleSort;
  window.toggleBurstView = app.features.review.toggleBurstView;
  window.openSpeciesEdit = app.features.review.openSpeciesEdit;
  window.saveSpeciesEdit = app.features.review.saveSpeciesEdit;
  window.cancelSpeciesEdit = app.features.review.cancelSpeciesEdit;
  window.undoLastAction = app.features.review.undoLastAction;
  window.askBurstConfirm = app.features.review.askBurstConfirm;
  window.burstAction = app.features.review.burstAction;
  window.undoBurstAction = app.features.review.undoBurstAction;
  window.toggleAffectedPanel = app.features.validate.toggleAffectedPanel;
  window.updateTimePreview = app.features.validate.updateTimePreview;
  window.toggleUnprocPanel = app.features.validate.toggleUnprocPanel;
  window.runValidation = app.features.validate.runValidation;
  window.toggleExportOption = app.features.export.toggleExportOption;
  window.toggleExportFilter = app.features.export.toggleExportFilter;
  window.startExport = app.features.export.startExport;
  window.closeExportModal = app.features.export.closeExportModal;
  window.confirmExport = app.features.export.confirmExport;
  window.syncExportFilenamePreview = app.features.export.syncExportFilenamePreview;
  // Download a single export artifact CSV by filename
  window.downloadFile = app.features.export.downloadFile;
}
